/**
 * HUSIN Marketplace — 30 Product Sources
 * 15 FAMOUS (well-known to Saudi shoppers)
 * 15 HIDDEN (reliable but hard for Saudis to shop directly)
 * Each source has a scraping strategy and category focus
 */

export const FAMOUS_SOURCES = [
  {
    id: 'amazon_sa',
    name: 'Amazon Saudi Arabia',
    baseUrl: 'https://www.amazon.sa',
    searchUrl: (q) => `https://www.amazon.sa/s?k=${encodeURIComponent(q)}&s=review-rank&language=en`,
    type: 'famous',
    categories: ['electronics', 'home', 'clothing', 'beauty', 'sports'],
    currency: 'SAR',
    flag: '🇸🇦',
    parser: 'amazon',
  },
  {
    id: 'noon_sa',
    name: 'Noon Saudi Arabia',
    baseUrl: 'https://www.noon.com',
    searchUrl: (q) => `https://www.noon.com/saudi-en/search/?q=${encodeURIComponent(q)}&sort%5Bby%5D=popularity`,
    type: 'famous',
    categories: ['electronics', 'home', 'clothing', 'beauty'],
    currency: 'SAR',
    flag: '🟡',
    parser: 'noon',
  },
  {
    id: 'namshi',
    name: 'Namshi',
    baseUrl: 'https://www.namshi.com',
    searchUrl: (q) => `https://www.namshi.com/saudi-en/search/?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['clothing', 'shoes', 'accessories', 'beauty'],
    currency: 'SAR',
    flag: '👗',
    parser: 'namshi',
  },
  {
    id: 'aliexpress',
    name: 'AliExpress',
    baseUrl: 'https://www.aliexpress.com',
    searchUrl: (q) => `https://www.aliexpress.com/wholesale?SearchText=${encodeURIComponent(q)}&SortType=total_tranpro_desc`,
    type: 'famous',
    categories: ['electronics', 'home', 'clothing', 'accessories', 'toys'],
    currency: 'USD',
    flag: '🇨🇳',
    parser: 'aliexpress',
  },
  {
    id: 'ebay',
    name: 'eBay',
    baseUrl: 'https://www.ebay.com',
    searchUrl: (q) => `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(q)}&_sop=12&LH_BIN=1`,
    type: 'famous',
    categories: ['electronics', 'collectibles', 'clothing', 'accessories'],
    currency: 'USD',
    flag: '🛍️',
    parser: 'ebay',
  },
  {
    id: 'shein',
    name: 'Shein',
    baseUrl: 'https://www.shein.com',
    searchUrl: (q) => `https://www.shein.com/pdsearch/${encodeURIComponent(q)}/`,
    type: 'famous',
    categories: ['clothing', 'accessories', 'beauty', 'home'],
    currency: 'USD',
    flag: '👘',
    parser: 'shein',
  },
  {
    id: 'farfetch',
    name: 'Farfetch',
    baseUrl: 'https://www.farfetch.com',
    searchUrl: (q) => `https://www.farfetch.com/sa/shopping/men/${encodeURIComponent(q)}-1.aspx`,
    type: 'famous',
    categories: ['luxury', 'clothing', 'shoes', 'accessories', 'jewelry'],
    currency: 'USD',
    flag: '💎',
    parser: 'farfetch',
  },
  {
    id: 'net_a_porter',
    name: 'NET-A-PORTER',
    baseUrl: 'https://www.net-a-porter.com',
    searchUrl: (q) => `https://www.net-a-porter.com/en-sa/shop/search?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['luxury', 'clothing', 'jewelry', 'beauty', 'accessories'],
    currency: 'SAR',
    flag: '👜',
    parser: 'net_a_porter',
  },
  {
    id: 'jarir',
    name: 'Jarir Bookstore',
    baseUrl: 'https://www.jarir.com',
    searchUrl: (q) => `https://www.jarir.com/sa-en/catalogsearch/result/?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['electronics', 'laptops', 'mobiles', 'books', 'office'],
    currency: 'SAR',
    flag: '📚',
    parser: 'jarir',
  },
  {
    id: 'extra',
    name: 'eXtra Electronics',
    baseUrl: 'https://www.extra.com',
    searchUrl: (q) => `https://www.extra.com/en-sa/search/?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['electronics', 'home_appliances', 'mobiles', 'laptops', 'gaming'],
    currency: 'SAR',
    flag: '📱',
    parser: 'extra',
  },
  {
    id: 'asos',
    name: 'ASOS',
    baseUrl: 'https://www.asos.com',
    searchUrl: (q) => `https://www.asos.com/search/?q=${encodeURIComponent(q)}&country=SA`,
    type: 'famous',
    categories: ['clothing', 'shoes', 'accessories', 'beauty'],
    currency: 'USD',
    flag: '🎨',
    parser: 'asos',
  },
  {
    id: 'hm',
    name: 'H&M',
    baseUrl: 'https://www2.hm.com',
    searchUrl: (q) => `https://www2.hm.com/en_gb/search-results.html?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['clothing', 'kids', 'home', 'accessories'],
    currency: 'USD',
    flag: '🏷️',
    parser: 'hm',
  },
  {
    id: 'apple',
    name: 'Apple Store',
    baseUrl: 'https://www.apple.com',
    searchUrl: (q) => `https://www.apple.com/sa/shop/search?q=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['electronics', 'mobiles', 'laptops', 'accessories'],
    currency: 'SAR',
    flag: '🍎',
    parser: 'apple',
  },
  {
    id: 'samsung',
    name: 'Samsung Saudi Arabia',
    baseUrl: 'https://www.samsung.com',
    searchUrl: (q) => `https://www.samsung.com/sa_en/search/?searchvalue=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['electronics', 'mobiles', 'home_appliances', 'laptops'],
    currency: 'SAR',
    flag: '📲',
    parser: 'samsung',
  },
  {
    id: 'zara',
    name: 'Zara',
    baseUrl: 'https://www.zara.com',
    searchUrl: (q) => `https://www.zara.com/sa/en/search?searchTerm=${encodeURIComponent(q)}`,
    type: 'famous',
    categories: ['clothing', 'shoes', 'accessories', 'kids', 'home'],
    currency: 'SAR',
    flag: '🛍️',
    parser: 'zara',
  },
]

export const HIDDEN_SOURCES = [
  {
    id: 'trendyol',
    name: 'Trendyol',
    baseUrl: 'https://www.trendyol.com',
    searchUrl: (q) => `https://www.trendyol.com/sr?q=${encodeURIComponent(q)}&sst=BEST_SELLER`,
    type: 'hidden',
    categories: ['clothing', 'shoes', 'home', 'beauty', 'accessories'],
    currency: 'USD',
    flag: '🇹🇷',
    parser: 'trendyol',
    hiddenReason: 'Turkish platform — huge catalog, not accessible easily from KSA',
  },
  {
    id: 'banggood',
    name: 'Banggood',
    baseUrl: 'https://www.banggood.com',
    searchUrl: (q) => `https://www.banggood.com/search/${encodeURIComponent(q)}.html?sortType=totalOrders`,
    type: 'hidden',
    categories: ['electronics', 'tools', 'toys', 'sports', 'home'],
    currency: 'USD',
    flag: '🔧',
    parser: 'banggood',
    hiddenReason: 'Chinese direct — great prices, unknown to most Saudi shoppers',
  },
  {
    id: 'ubuy',
    name: 'Ubuy Saudi Arabia',
    baseUrl: 'https://www.ubuy.com.sa',
    searchUrl: (q) => `https://www.ubuy.com.sa/en/search/?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['electronics', 'beauty', 'clothing', 'toys', 'sports'],
    currency: 'SAR',
    flag: '🌐',
    parser: 'ubuy',
    hiddenReason: 'Ships international brands to KSA — not widely known',
  },
  {
    id: 'desertcart',
    name: 'Desertcart Saudi Arabia',
    baseUrl: 'https://www.desertcart.sa',
    searchUrl: (q) => `https://www.desertcart.sa/products?query=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['electronics', 'beauty', 'clothing', 'home', 'toys'],
    currency: 'SAR',
    flag: '🏜️',
    parser: 'desertcart',
    hiddenReason: 'Imports hard-to-find items to KSA — niche but profitable',
  },
  {
    id: 'ounass',
    name: 'Ounass',
    baseUrl: 'https://www.ounass.com',
    searchUrl: (q) => `https://www.ounass.com/sa/search?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['luxury', 'clothing', 'shoes', 'accessories', 'beauty'],
    currency: 'SAR',
    flag: '✨',
    parser: 'ounass',
    hiddenReason: 'Premium luxury platform — Saudi focused but niche',
  },
  {
    id: 'yesStyle',
    name: 'YesStyle',
    baseUrl: 'https://www.yesstyle.com',
    searchUrl: (q) => `https://www.yesstyle.com/en/search.html?ck=searchPrd&keyword=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['beauty', 'skincare', 'clothing', 'accessories'],
    currency: 'USD',
    flag: '🇰🇷',
    parser: 'yestyle',
    hiddenReason: 'Korean beauty & fashion — huge demand in KSA, not easily accessible',
  },
  {
    id: 'jollychic',
    name: 'JollyChic',
    baseUrl: 'https://www.jollychic.com',
    searchUrl: (q) => `https://www.jollychic.com/list?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['clothing', 'accessories', 'beauty', 'kids'],
    currency: 'SAR',
    flag: '🎀',
    parser: 'jollychic',
    hiddenReason: 'Saudi-targeted but rarely discovered organically',
  },
  {
    id: 'mumzworld',
    name: 'Mumzworld',
    baseUrl: 'https://www.mumzworld.com',
    searchUrl: (q) => `https://www.mumzworld.com/en/search?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['baby', 'kids', 'maternity', 'toys', 'home'],
    currency: 'SAR',
    flag: '👶',
    parser: 'mumzworld',
    hiddenReason: 'Best baby/kids source in MENA — underutilized by Saudi shoppers',
  },
  {
    id: 'eyewa',
    name: 'Eyewa',
    baseUrl: 'https://www.eyewa.com',
    searchUrl: (q) => `https://www.eyewa.com/sa-en/search?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['eyewear', 'sunglasses', 'contact_lenses', 'accessories'],
    currency: 'SAR',
    flag: '👓',
    parser: 'eyewa',
    hiddenReason: 'Best eyewear prices in MENA — not commonly known',
  },
  {
    id: 'brands4less',
    name: 'Brands For Less',
    baseUrl: 'https://www.brandsforless.com',
    searchUrl: (q) => `https://www.brandsforless.com/en-sa/catalogsearch/result/?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['clothing', 'shoes', 'accessories', 'home'],
    currency: 'SAR',
    flag: '💸',
    parser: 'brands4less',
    hiddenReason: 'Up to 80% off branded items — extremely low source prices',
  },
  {
    id: 'romwe',
    name: 'Romwe',
    baseUrl: 'https://www.romwe.com',
    searchUrl: (q) => `https://www.romwe.com/pdsearch/${encodeURIComponent(q)}/`,
    type: 'hidden',
    categories: ['clothing', 'accessories', 'beauty', 'home'],
    currency: 'USD',
    flag: '💃',
    parser: 'romwe',
    hiddenReason: 'Ultra-cheap trendy fashion — Saudi buyers rarely access directly',
  },
  {
    id: 'zaful',
    name: 'Zaful',
    baseUrl: 'https://www.zaful.com',
    searchUrl: (q) => `https://www.zaful.com/search.html?q=${encodeURIComponent(q)}&sort_type=7`,
    type: 'hidden',
    categories: ['clothing', 'swimwear', 'accessories'],
    currency: 'USD',
    flag: '🌊',
    parser: 'zaful',
    hiddenReason: 'Niche fashion, unknown in Saudi market',
  },
  {
    id: 'fashionnova',
    name: 'Fashion Nova',
    baseUrl: 'https://www.fashionnova.com',
    searchUrl: (q) => `https://www.fashionnova.com/search?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['clothing', 'accessories'],
    currency: 'USD',
    flag: '⭐',
    parser: 'fashionnova',
    hiddenReason: 'US brand, no Saudi presence, high demand from Saudi women',
  },
  {
    id: 'cicihot',
    name: 'CiciHot',
    baseUrl: 'https://www.cicihot.com',
    searchUrl: (q) => `https://www.cicihot.com/search.html?q=${encodeURIComponent(q)}`,
    type: 'hidden',
    categories: ['clothing', 'accessories', 'shoes'],
    currency: 'USD',
    flag: '🔥',
    parser: 'cicihot',
    hiddenReason: 'Trendy fast fashion, completely unknown in KSA',
  },
  {
    id: 'rosegal',
    name: 'Rosegal',
    baseUrl: 'https://www.rosegal.com',
    searchUrl: (q) => `https://www.rosegal.com/search.html?q=${encodeURIComponent(q)}&sort_type=7`,
    type: 'hidden',
    categories: ['clothing', 'plus_size', 'accessories', 'beauty'],
    currency: 'USD',
    flag: '🌹',
    parser: 'rosegal',
    hiddenReason: 'Plus-size focus, very rare in KSA market',
  },
]

export const ALL_SOURCES = [...FAMOUS_SOURCES, ...HIDDEN_SOURCES]

// USD to SAR conversion rate (update periodically)
export const USD_TO_SAR = 3.75
